apiVersion: v1
kind: ConfigMap
metadata:
  name: factom-resolver-config
  labels:
    app: did
data:
  applicationContext.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <beans xmlns="http://www.springframework.org/schema/beans"
      xmlns:util="http://www.springframework.org/schema/util" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.0.xsd http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-2.0.xsd">

      <!-- UNIVERSAL RESOLVER SERVLET -->

      <bean name="UniResolver" class="uniresolver.local.LocalUniResolver">
      <property name="drivers">
      <util:map>
      <entry key="did-btcr"><ref bean="DidBtcrDriver" /></entry>
      <entry key="did-sov"><ref bean="DidSovDriver" /></entry>
      <entry key="did-uport"><ref bean="DidUportDriver" /></entry>
      <entry key="did-v1"><ref bean="DidV1Driver" /></entry>
      <entry key="did-ipid"><ref bean="DidIpidDriver" /></entry>
      <entry key="did-stack"><ref bean="DidStackDriver" /></entry>
      <entry key="did-erc725"><ref bean="DidErc725Driver" /></entry>
      <entry key="did-dom"><ref bean="DidDomDriver" /></entry>
      <entry key="dns-did"><ref bean="DnsDriver" /></entry>
      <entry key="did-jolo"><ref bean="DidJoloDriver" /></entry>
      <entry key="did-hacera"><ref bean="DidHaceraDriver" /></entry>
      <entry key="did-factom"><ref bean="DidFactomDriver" /></entry>
      </util:map>
      </property>
      </bean>

      <bean name="ResolveServlet" class="uniresolver.web.servlet.ResolveServlet">
      <property name="uniResolver" ref="UniResolver" />
      </bean>

      <bean name="PropertiesServlet" class="uniresolver.web.servlet.PropertiesServlet">
      <property name="uniResolver" ref="UniResolver" />
      </bean>

      <!-- DRIVERS (VIA DOCKER REST API) -->

      <bean id="DidBtcrDriver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="http://resolver-btcr.did/1.0/identifiers/$1" />
      <property name="propertiesUri" value="http://resolver-btcr.did/1.0/properties" />
      <property name="pattern" value="^(did:btcr:.+)$" />
      </bean>

      <bean id="DidSovDriver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="http://resolver-sov.did/1.0/identifiers/$1" />
      <property name="propertiesUri" value="http://resolver-sov.did/1.0/properties" />
      <property name="pattern" value="^(did:sov:(?:(?:\w[-\w]*(?::\w[-\w]*)*):)?(?:[1-9A-HJ-NP-Za-km-z]{21,22}))$" />
      </bean>

      <bean id="DidUportDriver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="http://resolver-uport.did/1.0/identifiers/$1" />
      <property name="pattern" value="^(did:uport:.+)$|^(did:muport:.+)$|^(did:eth:.+)$|^(did:ethr:.+)$" />
      </bean>

      <bean id="DidV1Driver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="https://genesis.testnet.veres.one/dids/$1" />
      <property name="pattern" value="^(did:v1:.+)$" />
      </bean>

      <bean id="DidIpidDriver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="https://ipfs.io/ipns/$1" />
      <property name="pattern" value="^did:ipid:(.+)$" />
      </bean>

      <bean id="DidStackDriver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="http://resolver-stack.did/1.0/identifiers/$1" />
      <property name="propertiesUri" value="http://resolver-stack.did/1.0/properties" />
      <property name="pattern" value="^(did:stack:.+)$" />
      </bean>

      <bean id="DidErc725Driver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="http://resolver-erc725.did:8080/1.0/identifiers/$1" />
      <property name="propertiesUri" value="http://resolver-erc725.did:8080/1.0/properties" />
      <property name="pattern" value="^(did:erc725:.+)$" />
      </bean>

      <bean id="DidDomDriver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="http://driver-did-dom:8080/1.0/identifiers/$1" />
      <property name="propertiesUri" value="http://driver-did-dom:8080/1.0/properties" />
      <property name="pattern" value="^(did:dom:.+)$" />
      </bean>

      <bean id="DnsDriver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="http://resolver-dns.did/1.0/identifiers/$1" />
      <property name="propertiesUri" value="http://resolver-dns.did/1.0/properties" />
      <property name="pattern" value="^((?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*(?:[A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]))$" />
      </bean>

      <bean id="DidJoloDriver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="http://resolver-jolo.did/1.0/identifiers/$1" />
      <property name="pattern" value="^(did:jolo:.+)$" />
      </bean>

      <bean id="DidHaceraDriver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="http://resolver-hacera.did/1.0/identifiers/$1" />
      <property name="pattern" value="^(did:hcr:.+)$" />
      </bean>

      <bean id="DidFactomDriver" class="uniresolver.driver.http.HttpDriver">
      <property name="resolveUri" value="http://resolver-factom.did/1.0/identifiers/$1" />
      <property name="propertiesUri" value="http://resolver-factom.did/1.0/properties" />
      <property name="pattern" value="^(did:factom:.+)$" />
      </bean>

    </beans>
