{{- range .Values.resolvers }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: did-{{ .name }}
  labels:
    app.kubernetes.io/name: did
spec:
  replicas: 1
  selector:
    matchLabels:
      app: did
      component: resolvers
      resolver: {{ .name }}
  template:
    metadata:
      labels:
        app: did
        component: resolvers
        resolver: {{ .name }}
    spec:
      imagePullSecrets:
        - name: dockerhub
      {{- if .mountCustomConfig }}
      volumes:
      - name: factom-config
        configMap:
          name: factom-resolver-config
      {{- end }}
      containers:
        - name: {{ .name }}
          image: {{ .image.repository }}:{{ .image.tag }}
          imagePullPolicy: {{.image.imagePullPolicy}}
          ports:
            - name: {{ .name }}-http
              containerPort: 8080
              protocol: TCP
          environment:
            {{- range .environment }}
            name: {{ .name }}
            value: {{ .value }}
            {{- end }}
          {{- if .mountCustomConfig }}
          volumeMounts:
          - name: factom-config
            subPath: applicationContext.xml
            mountPath: /opt/uni-resolver-java/uni-resolver-web/src/main/webapp/WEB-INF/applicationContext.xml
          {{- end }}
---
{{- end }}
