{{ range .Values.resolvers }}
apiVersion: v1
kind: Service
metadata:
  name: resolver-{{ .name }}
  labels:
    app.kubernetes.io/name: did
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: did
    component: resolvers
    resolver: {{ .name }}
---
{{ end }}
